data:
    dataset: "interhand"
    dataset_path: "/data/hand_data/interhand2.6m" 
    num_workers: 4

model:
    hid_dim: 2056
    emd_dim: 512
    coords_dim: 64
    num_layer: 7
    n_head: 4
    dropout: 0.25
    ema_rate: 0.999
    ema: False
    var_type: fixedsmall
    skips: [1, 3, 5, 6]
    downsample: 1

diffusion:
    beta_schedule: linear
    beta_start: 0.0001
    beta_end: 0.01
    num_diffusion_timesteps: 129

training:
    batch_size: 256
    lr_gamma: 0.9
    lr: 0.001
    decay: 60
    n_epochs: 80
    n_iters: 5000000
    snapshot_freq: 5000
    validation_freq: 2000
    vis: False
    vis_batch: 100

testing:
    test_times: 1
    test_timesteps: 42 
    test_num_diffusion_timesteps: 126 
    vis: True
    vis_batch: 2500
    vis_epoch: 4
    anti_pen: True

optim:
    decay: 20
    optimizer: "Adam"
    lr: 0.001
    lr_gamma: 0.9
    amsgrad: false
    eps: 0.00000001
    grad_clip: 4.0
